name: CoreBackendIdentity-heroku-deploy

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.0.0
    - name: Build the Docker image
      run: docker build IdentityServer --file IdentityServer/Dockerfile.heroku -t virtualcollege-identity:$(date +%s)
    
    - name: See docker images
      run: docker images
